In [2]:
import tensorflow as tf


In [11]:
'''
    example for broadcast
    
    shapes:
        [maxlen, hidden_units] * [maxlen, 1]  = [maxlen, hidden_units]
        
        [batch_size, maxlen, hidden_units] * [batch_size, maxlen, 1] = [batch_size, maxlen, hidden_units]
'''

input_1 = tf.constant([[1, 2], [3, 4]])
mask_1 = tf.constant([[1], [0]])
output_1 = input_1 * mask_1  # [2, 2] * [2, 1] = [2, 2]


input_2 = tf.constant([
    [[1, 2, 3], [3, 4, 5]],
    [[0, 1, 1], [2, 2, 0]]]
    )  # [2, 2, 3]
mask_2 = tf.constant([
    [[1], [0]],
    [[0], [1]]])  # [2, 2, 1]
output_2 = input_2 * mask_2  # [2, 2, 3] * [2, 2, 1] = [2, 2, 3]


input_3 = tf.constant([
    [[1, 2, 3], [3, 4, 5]],
    [[0, 1, 1], [2, 2, 0]]]
    )  # [2, 2, 3]
mask_3 = tf.constant(
    [[1, 1, 1], [0, 0, 0]])
output_3 = input_3 * mask_3  # [2, 2, 3] * [2, 3] = [2, 2, 3]  最后两维相乘
mean, variance = tf.nn.moments(input_3, [-1], keep_dims=True)

with tf.Session() as sess:
    print(sess.run(output_1))
    print('****'*4)
    print(sess.run(output_2))
    print('****'*4)
    print(sess.run(output_3))
    print('****'*4)
    print(sess.run(mean))
    print('****'*4)
    print(sess.run(variance))
    

[[1 2]
 [0 0]]
****************
[[[1 2 3]
  [0 0 0]]

 [[0 0 0]
  [2 2 0]]]
****************
[[[1 2 3]
  [0 0 0]]

 [[0 1 1]
  [0 0 0]]]
****************
[[[2]
  [4]]

 [[0]
  [1]]]
****************
[[[0]
  [0]]

 [[0]
  [1]]]


In [6]:
'''
    reduce_sum
'''


input = tf.constant([
    [1, 2, 3], [3, 4, 5],
    [0, 1, 1]]
    )  # [3, 3]

diag_vals = tf.ones_like(input)
output = tf.linalg.LinearOperatorLowerTriangular(diag_vals).to_dense()


with tf.Session() as sess:
    print(sess.run(output))
    
    

[[1 0 0]
 [1 1 0]
 [1 1 1]]


In [11]:
import tensorflow as tf


input_length = [2, 3]
T = 5
N = 2
inputs_mask = tf.sequence_mask(input_length, T, tf.float32)
inputs_mask = tf.reshape(inputs_mask, [N, T, 1, 1])

with tf.Session() as sess:
    print(sess.run(inputs_mask))



[[[[1.]]

  [[1.]]

  [[0.]]

  [[0.]]

  [[0.]]]


 [[[1.]]

  [[1.]]

  [[1.]]

  [[0.]]

  [[0.]]]]
